CREATE Database P2UTechTest
GO

USE P2UTechTest
GO

CREATE Table Users
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserName nvarchar(50) NOT NULL
)

CREATE Table Currencies
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CountryCode nvarchar(3) NOT NULL
)

CREATE TABLE ConversionRates
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ConvertFromId INT NOT NULL,
ConvertToId INT NOT NULL,
Rate DECIMAL(10,4) NOT NULL,
FOREIGN KEY (ConvertFrom) REFERENCES Currencies(Id),
FOREIGN KEY (ConvertTo) REFERENCES Currencies(Id)
)

CREATE TABLE ConversionLogs
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ConversionRateId INT NOT NULL,
Rate DECIMAL(10,4) NOT NULL,
ValueFrom DECIMAL(18,2) NOT NULL,
ValueTo DECIMAL(18,2) NOT NULL,
ConversionDate DATETIME NOT NULL,
UserId INT NOT NULL,
FOREIGN KEY (ConversionID) REFERENCES ConversionRates(Id),
FOREIGN KEY (UserId) REFERENCES Users(Id)
)